---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/RedundantReturn:
  Exclude:
  - lib/avm/issue/unblock.rb
  - lib/avm/issue/undefine.rb
  - lib/avm/listeners/issue_auto_assign.rb
  - lib/avm/listeners/issue_auto_unblock/issue_update.rb
  - lib/avm/listeners/issue_auto_undefine/issue_update.rb
  - lib/avm/listeners/issue_dependencies_section_check.rb
  - lib/avm/listeners/issue_motivation_check.rb
Style/RedundantStringEscape:
  Exclude:
  - lib/avm/issue/dependencies_section_check.rb
  - lib/avm/issue/motivation_check.rb
  - test/lib/avm/listeners/issue_auto_unblock_test.rb
  - test/lib/avm/listeners/issue_dependencies_section_check_test.rb
Style/StringConcatenation:
  Exclude:
  - config/initializers/redmine_plugins_helper.rb
  - lib/redmine_avm/patches/issue_patch.rb
  - test/lib/avm/listeners/issue_auto_unblock_test.rb
