---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/StringConcatenation:
  Exclude:
  - config/initializers/redmine_plugins_helper.rb
  - lib/redmine_avm/patches/issue_patch.rb
  - test/lib/avm/listeners/issue_auto_unblock_test.rb
